### ISSUE TITLE
Help debugging "tls: bad certificate" errors

### ISSUE THREAD

**Issue by asomers** [zrepl/zrepl#517]
My zrepl instance is failing with `tls: bad certificate` errors. The logs say much more than that.  How can I debug the problem to figure out what's wrong with my certs?

My setup is a single server with several pull jobs and 8 other servers with one source job apiece.  They all use self-signed TLS certificates.  The setup was previously working fine, until I replaced the pull server.  I transferred the existing destination dataset with zfs send/recv, transfered the zrepl.yml file, generated new certificates and deployed them.  Now, on the source machine the logs look like this:
```
2021-09-17T20:25:00.339795+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=job span=Uv38$bWRc$bWRc.RRg7.L7R2.EwCY msg="start replication"
2021-09-17T20:25:00.339941+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=repl span=Uv38$bWRc$bWRc.RRg7.L7R2.EwCY.saFp msg="start planning"
2021-09-17T20:25:00.645182+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=rpc.ctrl span=Uv38$bWRc$bWRc.RRg7.L7R2 msg="cannot connect" err="could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate"
2021-09-17T20:25:00.645217+00:00 PULLHOST zrepl[32409] 2021-09-17T20:25:00Z [ERRO][recv_SOURCEHOST][rpc.ctrl][Uv38$bWRc$bWRc.RRg7.L7R2]: cannot connect err="could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate"
2021-09-17T20:25:00.645467+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=repl span=Uv38$bWRc$bWRc.RRg7.L7R2.EwCY.saFp msg="error listing sender filesystems" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate\"" errType=*status.Error
2021-09-17T20:25:00.645508+00:00 PULLHOST zrepl[32409] 2021-09-17T20:25:00Z [ERRO][recv_SOURCEHOST][repl][Uv38$bWRc$bWRc.RRg7.L7R2.EwCY.saFp]: error listing sender filesystems err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate\"" errType="*status.Error"
2021-09-17T20:25:00.645658+00:00 PULLHOST zrepl[32409] 2021-09-17T20:25:00Z [ERRO][recv_SOURCEHOST][repl][Uv38$bWRc$bWRc.RRg7.L7R2.EwCY]: most recent error in this attempt err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate\"" attempt_number="0"
2021-09-17T20:25:00.645666+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=repl span=Uv38$bWRc$bWRc.RRg7.L7R2.EwCY msg="most recent error in this attempt" attempt_number=0 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate\""
2021-09-17T20:25:00.645743+00:00 PULLHOST zrepl[32409] 2021-09-17T20:25:00Z [ERRO][recv_SOURCEHOST][repl][Uv38$bWRc$bWRc.RRg7.L7R2.EwCY]: temporary connectivity-related error identified, start waiting for reconnect attempt_number="0" deadline="2021-09-17 20:35:00.645669946 +0000 UTC m=+1158.970501483"
2021-09-17T20:25:00.645765+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=repl span=Uv38$bWRc$bWRc.RRg7.L7R2.EwCY msg="temporary connectivity-related error identified, start waiting for reconnect" attempt_number=0 deadline=2021-09-17T20:35:00.645669946Z
2021-09-17T20:25:00.951495+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=rpc.data span=Uv38$bWRc$YW7d$YW7d.RLLY msg="ping failed" err="could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate"
2021-09-17T20:25:00.951536+00:00 PULLHOST zrepl[32409] 2021-09-17T20:25:00Z [ERRO][recv_SOURCEHOST][rpc.data][Uv38$bWRc$YW7d$YW7d.RLLY]: ping failed err="could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate"
2021-09-17T20:25:00.951599+00:00 PULLHOST zrepl[32409] 2021-09-17T20:25:00Z [ERRO][recv_SOURCEHOST][rpc.ctrl][Uv38$bWRc$YW7d$YW7d.RLLY]: ping failed err="rpc error: code = Canceled desc = latest balancer error: connection error: desc = \"transport: Error while dialing could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate\""
2021-09-17T20:25:00.951627+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=rpc.ctrl span=Uv38$bWRc$YW7d$YW7d.RLLY msg="ping failed" err="rpc error: code = Canceled desc = latest balancer error: connection error: desc = \"transport: Error while dialing could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate\""
2021-09-17T20:25:00.951765+00:00 PULLHOST zrepl[32409] 2021-09-17T20:25:00Z [ERRO][recv_SOURCEHOST][repl][Uv38$bWRc$bWRc.RRg7.L7R2.EwCY]: reconnecting failed, aborting run attempt_number="0" err="sender is not reachable: control and data rpc failed to respond to ping rpcs"
2021-09-17T20:25:00.951778+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=repl span=Uv38$bWRc$bWRc.RRg7.L7R2.EwCY msg="reconnecting failed, aborting run" attempt_number=0 err="sender is not reachable: control and data rpc failed to respond to ping rpcs"
2021-09-17T20:25:00.951993+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=job span=Uv38$bWRc$bWRc.RRg7.L7R2.ynsf msg="start pruning sender"
2021-09-17T20:25:00.952195+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=job span=Uv38$bWRc$bWRc.RRg7.L7R2.ynsf msg="finished pruning sender"
2021-09-17T20:25:00.952384+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=job span=Uv38$bWRc$bWRc.RRg7.L7R2.jxWn msg="start pruning receiver"
2021-09-17T20:25:00.952533+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=job span=Uv38$bWRc$bWRc.RRg7.L7R2.jxWn msg="finished pruning receiver"
2021-09-17T20:25:00.952713+00:00 PULLHOST zrepl[32410]: job=recv_SOURCEHOST subsystem=job span=Uv38$bWRc$bWRc.RRg7 msg="wait for wakeups"
```
And on the source hosts, like this:
```
2021-09-17T20:25:00.596100+00:00 SOURCEHOST zrepl[1905]: job=snap_and_serve_PULLHOST subsystem=transportmux span=8x/p$Wh6Z$Wh6Z.eh8S msg="accept error" err="tls: client didn't provide a certificate" errType=*errors.errorString
2021-09-17T20:25:00.596176+00:00 SOURCEHOST zrepl[1904] 2021-09-17T20:25:00Z [ERRO][snap_and_serve_PULLHOST][transportmux][8x/p$Wh6Z$Wh6Z.eh8S]: accept error errType="*errors.errorString" err="tls: client didn't provide a certificate"
2021-09-17T20:25:00.902540+00:00 SOURCEHOST zrepl[1905]: job=snap_and_serve_PULLHOST subsystem=transportmux span=8x/p$Wh6Z$Wh6Z.eh8S msg="accept error" err="tls: client didn't provide a certificate" errType=*errors.errorString
2021-09-17T20:25:00.902646+00:00 SOURCEHOST zrepl[1904] 2021-09-17T20:25:00Z [ERRO][snap_and_serve_PULLHOST][transportmux][8x/p$Wh6Z$Wh6Z.eh8S]: accept error err="tls: client didn't provide a certificate" errType="*errors.errorString"
```

**Comment by problame** [comment]
Did this coincide with an update to zrepl 0.3 or newer?

> Go 1.15 changed the default TLS validation policy to require Subject Alternative Names (SAN) in certificates. The openssl commands we provided in the quick-start guides up to and including the zrepl 0.3 docs seem not to work properly. If you encounter certificate validation errors regarding SAN and wish to continue to use your old certificates, start the zrepl daemon with env var GODEBUG=x509ignoreCN=0. Alternatively, generate new certificates with SANs (see both options int the TLS transport docs ).

https://zrepl.github.io/changelog.html#release-0-3

**Comment by asomers** [comment]
No, it worked with zrepl 0.3, adding that environment variable doesn't help, and the cert has a Subject Alternative Name.  Is there any way to get a better error message ?

**Comment by problame** [comment]
Are you able to build zrepl from source?
The error in questions stems from this line here:
https://github.com/zrepl/zrepl/blob/95fc299733c0833ba2d12d023586fa0fb1cb69c8/transport/tls/connect_tls.go#L51

And the error format string is controlled by

https://github.com/zrepl/zrepl/blob/95fc299733c0833ba2d12d023586fa0fb1cb69c8/transport/tls/connect_tls.go#L0-L1

You can use

```
return hsIOErr(err, "error reading protocol banner length: %#v", err)
```
or
```

import	"github.com/kr/pretty"

...

return hsIOErr(err, "error reading protocol banner length: %s", pretty.Sprint(err))
```

to get a prettier error.

Please report back or [hop on the Matrix channel](https://matrix.to/#/!souMIYnndmPnJcOnqo:matrix.org?via=cschwarz.com&via=matrix.org&via=koti.vuorio.org) for help.

**Comment by asomers** [comment]
The build fails with `transport/tls/connect_tls.go:51:10: undefined: hsIOErr`.  I apologize because I don't know Go.  I'm probably missing something completely obvious.  Could you please help?

**Comment by problame** [comment]
I pushed a commit with enough stderr debugging for you.

If you are on FreeBSD, the `daemon` utility used by the `rc.d` should store the stderr output somewhere. 
If not, please adjust the `rc.d` script and propagate the change to the maintainer.

On Linux, stderr lands in `sudo journalctl -u zrepl.service`.

Please let me know if the build succeeds now.

**Comment by asomers** [comment]
@problame that patch works, and now I get messages like this on the pull host:
```
HandshakeMessage.DecodeReader error: *tls.permanentError
subsystem=rpc.data span=Uv38$hikX$6S2e$6S2e.V21h msg="ping failed" err="could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate"
&tls.permanentError{
   err: &net.OpError{
       Op:     "remote error",
       Net:    "",
       Source: nil,
       Addr:   nil,
       Err:    tls.alert(0x2a),
   }, HandshakeConnecter error: *versionhandshake.HandshakeError
#011could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate
#011could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate
#011&versionhandshake.HandshakeError{msg:"could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate", IOError:error(nil), isAcceptError:false}
2021-09-20T19:52:25Z [ERRO][<SOURCE HOST>][rpc.ctrl][Uv38$hikX$hikX.eOgl.xZbk]: cannot connect err="could not decode protocol banner: error reading protocol banner length: remote error: tls: bad certificate"
```
Does that mean anything to you?

**Comment by problame** [comment]
So that tls.permanentError is merely the SSL Alert code `42 bad certificate`. (https://techcommunity.microsoft.com/t5/iis-support-blog/ssl-tls-alert-protocol-and-the-alert-codes/ba-p/377132)

So we'd probably need more debug logging on the source side as well, sorry about that.

I found https://github.com/etcd-io/etcd/issues/9785 in etcd (also Go) where the root cause was that the key usage fields in the TLS certs was incorrect.

Let me code up a patch that adds source side stderr debugging so that we know the root cause of this and can have better log messages in the future. Please do not delete the certs you are currently using.

**Comment by problame** [comment]
@asomers sorry for taking so long to follow up on this. I posted an updated version of the patch that adds some accept-side debugging as well. The source side stderr output _could_ be helpful.
However, looking at the log output you posted initially:
```
2021-09-17T20:25:00.596100+00:00 SOURCEHOST zrepl[1905]: job=snap_and_serve_PULLHOST subsystem=transportmux span=8x/p$Wh6Z$Wh6Z.eh8S msg="accept error" err="tls: client didn't provide a certificate" errType=*errors.errorString
```
From the perspective of the `source`, the client did not present a TLS certificate.
That error is straight from the Go standard library.
I don't think there is an option to configure more verbose logging for the standard library TLS stack.
So, if the updated patch doesn't reveal anything new, I'm not sure how we can proceed.

**Comment by asomers** [comment]
I still can't find anything.  Can you at least determine which file the `pull` side things is bad?  Is it the ca, the cert, or the key?

**Comment by asomers** [comment]
I don't think it's the key usage fields that are to blame, because they're the same as the old server's certificate.  When I dump the old server's and the new server's certs, they're the same except for the CN and the binary bits.

**Comment by asomers** [comment]
Are there any other CLI programs based on Go's standard library TLS implementations that can validate a certificate?  Maybe one of those would give some insight.

**Comment by problame** [comment]
That your (pull) job's cert uses the source's CN?
The `server.client_cn` controls which client CNs are allowed to connect.

**Comment by asomers** [comment]
So last week I tried regenerating all certificates.  This time everything works.  However, `openssl x509` doesn't show any differences (except for the binary bits, of course) between the old and new certs.  So I still have no idea why it didn't work before.

**Comment by jbliesener** [comment]
Could it be that you regenerated and installed the certificate but did not restart zrepl? In that case, the old certificate remains in use...

I have this issue regularly when my Let's Encrypt certificate is renewed automatically. I need to restart zrepl to pick up the new one.

**Comment by problame** [comment]
The problem is that I don't see a way how zrepl can improve on this, since

1. the underlying Go libraries provide no better error messages and
2. the various fprintf's to stderr that I added for you didn't help us with debugging either.

Please close this issue unless you have an idea how we can improve this experience.

**Comment by asomers-ax** [comment]
My only idea is to identify which certificate Go didn't like.  Is there a way to do that?

**Comment by problame** [comment]
I don't think there is a way. And since your certs worked [with the minimal Go TLS client](https://github.com/zrepl/zrepl/issues/517#issuecomment-939298941) I think it's most likely the paths in the config were incorrect, or the daemon didn't reload.
